# Generated by Django 5.1.7 on 2025-08-26 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='valid',
            new_name='verified',
        ),
    ]
