# Generated by Django 5.1.7 on 2025-08-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_valid_customuser_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reset_password',
            field=models.BooleanField(default=False),
        ),
    ]
